-- MySQL Script generated by MySQL Workbench
-- Thu Dec  8 11:27:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tpfinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpfinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpfinal` DEFAULT CHARACTER SET utf8 ;
USE `tpfinal` ;

-- -----------------------------------------------------
-- Table `tpfinal`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinal`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `idade_aluno` INT(3) NOT NULL,
  `peso_aluno` FLOAT NOT NULL,
  `altura_aluno` FLOAT NOT NULL,
  `objetivo_aluno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
